### PR TITLE
fix: use of depreciated function "inline"

### PR DESCRIPTION
**Pull request by mrglover**
Updated the code to use the newer "fromInline" instead of depreciated "inline".

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

**Review by peterwoodworth — APPROVED** [review]
Thanks for the PR!

**Comment by peterwoodworth** [comment]
Hey. @mrglover, thanks again for submitting these fixes. Could you please add another commit which is semantic? Feel free to use the same title as this issue. Sorry about that

**Review by peterwoodworth — CHANGES_REQUESTED** [review]
Please use a semantic commit message

**Comment by ryparker** [comment]
Changes implemented in https://github.com/aws-samples/aws-cdk-intro-workshop/pull/258

**Pull request closed without merging**
