### PR TITLE
fix: Update 1000-setting-up.md

### PR DESCRIPTION
**Pull request by kayuapi**
Synthesise the app locally to emit the CloudFormation template for review.

Fixes # 

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

**Comment by peterwoodworth** [comment]
Hey @kayuapi, sorry for the long wait here. Why do you want to see this change?

**Comment by kayuapi** [comment]
> Hey @kayuapi, sorry for the long wait here. Why do you want to see this change?



from https://docs.aws.amazon.com/cdk/latest/guide/hello_world.html and 

https://stackoverflow.com/questions/68434528/what-is-the-purpose-of-app-synth-in-aws-cdk
> It is optional (though good practice) to synthesize before deploying. The AWS CDK synthesizes your stack before each deployment.

also, in the python example, the document includes `app.synth()`, 
ref: https://cdkworkshop.com/30-python/70-advanced-topics/200-pipelines/1000-setting-up.html

**Comment by peterwoodworth** [comment]
The python example includes `app.synth()` because that is included in the python build by default when you create the CDK app in Python. 

> It is optional (though good practice) to synthesize before deploying
This means you want to examine the CloudFormation template which is synthesized by your CDK app before deploying to ensure that it's what you want. This is most typically achieved by running `cdk synth` in the command line. This step is never necessary and doesn't affect your deployment.

So because of this, we don't want to put `app.synth()` in our code because we can achieve the same thing with `cdk synth`. I hope this clears any misunderstandings up!

If you'd still like to contribute, we could potentially change the wording here to make the purpose of synthesizing more clear. What do you think @kayuapi?

**Comment by kayuapi** [comment]
Thank you for the explanation, @peterwoodworth ! Appreciate it because it enhances my understanding!

> The python example includes app.synth() because that is included in the python build by default when you create the CDK app in Python.

Is there a reason why `app.synth() ` is included in the python build by default? I think we can avoid putting app.synth() in the python default build because we can achieve the same thing with `cdk synth`.

**Comment by peterwoodworth** [comment]
> This step is never necessary and doesn't affect your deployment.

I need to correct this to "This step is only necessary in Python". Upon some investigation, I found that this line of code is necessary for python cdk to create the files in the `cdk.out` directory.

To be honest, I have no clue why this is required in only Python. I know that `app.synth()` used to be a required part of deploying for all languages, but hasn't been the case since I've started working on the CDK. There must be some specific reason I'm not aware of that it's still required in Python, but knowing _why_ is pretty trivial

Thank you for following up with that question @kayuapi, you helped me learn something here. I'm going to close this PR now, but feel free to ping me if you have any additional questions 😄

**Pull request closed without merging**
