### PR TITLE
Moved instructions from 20-typscript to be under 70-construct-hub

### PR DESCRIPTION
**Pull request by kingslyt**
Fixes # 

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT-0 License].

[MIT-0 License]: https://github.com/aws/mit-0/blob/master/MIT-0

### CODE REVIEW

**Comment by wasaymabood786** [comment]
approved

**Review by wasaymabood786 — APPROVED** [review]

**Review by wasaymabood786 — APPROVED** [review]
ship it

**Review by wasaymabood786 — APPROVED** [review]
approved

**Comment by kingslyt** [comment]
Incorrect Merge request target, hence closing

**Pull request closed without merging**
