### PR TITLE
Updating TypeScript workshop to Node 20

### PR DESCRIPTION
**Pull request by SamWSoftware**
- Updating the lambdas to use Node 20 as node 14 is not supported.
- Updating lambdas to use NodejsFunction as this allows the use of typescript as the lambda code
- Updating of all lambda code to typescript
- Updating of all of the workshop docs to match these above requirements
- Extension of the testing section to increase clarity of tests.

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT-0 License].

[MIT-0 License]: https://github.com/aws/mit-0/blob/master/MIT-0

### CODE REVIEW

**Comment by kellertk** [comment]
Hi @SamWSoftware, thanks for this PR! Since this is a larger one, reviewing this will take some time.

**Review by kellertk — CHANGES_REQUESTED** [review]
The move to a L3 construct for the Lambda function is a good idea, and I think I'm supportive of what you're trying to do in general. I need to deploy and test this in detail, the diffs are a lot longer here because you've changed `'` to `"` in many places, which is causing a lot of noise. Can you revise your PR to include only substantive changes, and not unnecessarily change code style? This would mean leaving quotes alone, minimizing whitespace changes, not adding commas where they aren't required for TS, etc. If you want to correct code style, we can do that too, but we should split that out into its own PR.

**Comment by SamWSoftware** [comment]
I'll go through and try and remove any style changes now.

**Comment by SamWSoftware** [comment]
That should be all of the style changes done to reduce the PR changes. Let me know if there are other bits that you want changing!

**Comment by SamWSoftware** [comment]
Bump

**Pull request closed without merging**
